global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080

  # - job_name: 'node-exporter'
    # scrape_interval: 15s
    # scrape_timeout: 10s
    # metrics_path: /metrics
    # static_configs:
    # - targets: ['localhost:9100']
    
  # - job_name: 'docker'
    # static_configs:
      # - targets: ['localhost:9323']
    
  # - job_name: 'mysql'
    # - targets: ['localhost:9104']
    