version: "3.8"
services:
  web-1:
    build:
        dockerfile: Dockerfile
        context: .
    container_name: "web-1"
    restart: "no"
    ports:
      - 3001:3000
    networks:
      - overlay1
      
  web-2:
    build:
        dockerfile: Dockerfile
        context: .
    container_name: "web-2"
    restart: "no"
    ports:
      - 3002:3000
    networks:
      - overlay1
      
  nginxserver:
    image: nginx:1.19.0
    container_name: nginxserver
    restart: on-failure
    networks:
      - overlay1
    volumes:
      - "../loadbalancer/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "3100:8080"

networks:
  overlay1:
